# Generated by Django 5.2.15 on 2026-06-28 09:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('everyday', 'Everyday'), ('savings', 'Savings'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='everyday', max_length=20)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_start', models.DateField(help_text='First day of the month.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month_start'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('budget_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budget.budgetmonth')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budget.category')),
            ],
            options={
                'ordering': ['category__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.categorygroup'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('goal_type', models.CharField(choices=[('needed_for_spending', 'Needed for spending'), ('savings_balance', 'Savings balance'), ('monthly_savings_builder', 'Monthly savings builder')], default='needed_for_spending', max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('repeat_interval_months', models.PositiveIntegerField(blank=True, help_text='e.g. 3 for a quarterly bill. Blank = one-off.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budget.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'category__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('cleared', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='budget_acco_user_id_81dd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmonth',
            index=models.Index(fields=['user', 'month_start'], name='budget_budg_user_id_6feca4_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('user', 'month_start'), name='unique_user_month'),
        ),
        migrations.AddIndex(
            model_name='budgetassignment',
            index=models.Index(fields=['user', 'budget_month'], name='budget_budg_user_id_938a3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetassignment',
            constraint=models.UniqueConstraint(fields=('user', 'budget_month', 'category'), name='unique_user_month_category'),
        ),
        migrations.AddIndex(
            model_name='categorygroup',
            index=models.Index(fields=['user', 'sort_order'], name='budget_cate_user_id_e5e764_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'category_group', 'sort_order'], name='budget_cate_user_id_689ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_active', 'due_date'], name='budget_goal_user_id_33a81c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='budget_tran_user_id_fcff6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'date'], name='budget_tran_user_id_40c685_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account', 'date'], name='budget_tran_user_id_534822_idx'),
        ),
    ]
