# Generated by Django 5.2.15 on 2026-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
