# Generated by Django 5.2.15 on 2026-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_transaction_is_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
