# Generated by Django 5.2.15 on 2026-06-29 13:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_transaction_reconciled_transaction_reconciled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('monthly_income_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use your recent average monthly income.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('expense', 'Monthly expense'), ('income', 'Monthly income'), ('one_off', 'One-off upfront cost')], default='expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('replaces_current', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_lines', to='budget.category')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['user', 'is_active'], name='budget_scen_user_id_9f2469_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioline',
            index=models.Index(fields=['user', 'scenario'], name='budget_scen_user_id_4c616a_idx'),
        ),
    ]
