# Generated by Django 5.2.15 on 2026-06-29 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_scenario_scenarioline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='budgetassignment',
            name='unique_user_month_category',
        ),
        migrations.RemoveConstraint(
            model_name='budgetmonth',
            name='unique_user_month',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='budget_acco_user_id_81dd6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetassignment',
            name='budget_budg_user_id_938a3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='budgetmonth',
            name='budget_budg_user_id_6feca4_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='budget_cate_user_id_689ba0_idx',
        ),
        migrations.RemoveIndex(
            model_name='categorygroup',
            name='budget_cate_user_id_e5e764_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='budget_goal_user_id_33a81c_idx',
        ),
        migrations.RemoveIndex(
            model_name='scenario',
            name='budget_scen_user_id_9f2469_idx',
        ),
        migrations.RemoveIndex(
            model_name='scenarioline',
            name='budget_scen_user_id_4c616a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='budget_tran_user_id_fcff6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='budget_tran_user_id_40c685_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='budget_tran_user_id_534822_idx',
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetassignment',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetmonth',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_months', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='goal',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='scenarioline',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_lines', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.budget'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['budget', 'is_active'], name='budget_acco_budget__d7ecac_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetassignment',
            index=models.Index(fields=['budget', 'budget_month'], name='budget_budg_budget__1847e8_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmonth',
            index=models.Index(fields=['budget', 'month_start'], name='budget_budg_budget__7ccace_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['budget', 'category_group', 'sort_order'], name='budget_cate_budget__be0664_idx'),
        ),
        migrations.AddIndex(
            model_name='categorygroup',
            index=models.Index(fields=['budget', 'sort_order'], name='budget_cate_budget__65013d_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['budget', 'is_active', 'due_date'], name='budget_goal_budget__cddf79_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['budget', 'is_active'], name='budget_scen_budget__1534fc_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioline',
            index=models.Index(fields=['budget', 'scenario'], name='budget_scen_budget__962faa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget', 'date'], name='budget_tran_budget__0bac3b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget', 'category', 'date'], name='budget_tran_budget__f0d043_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['budget', 'account', 'date'], name='budget_tran_budget__6e5ca3_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetassignment',
            constraint=models.UniqueConstraint(fields=('budget_month', 'category'), name='unique_month_category'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('budget', 'month_start'), name='unique_budget_month'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner', 'is_default'], name='budget_budg_owner_i_cc4144_idx'),
        ),
    ]
