# Generated by Django 5.2.15 on 2026-06-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_backfill_budgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='budgetassignment',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='budgetmonth',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_months', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='categorygroup',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='scenarioline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_lines', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.budget'),
        ),
    ]
