# Generated by Django 5.2.15 on 2026-07-01 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_memberships(apps, schema_editor):
    Budget = apps.get_model("budget", "Budget")
    BudgetMembership = apps.get_model("budget", "BudgetMembership")
    for budget in Budget.objects.all():
        BudgetMembership.objects.get_or_create(
            budget=budget, user=budget.owner, defaults={"role": "owner"}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_user_nullable_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='budget.budget')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'user__username'],
                'indexes': [models.Index(fields=['user'], name='budget_budg_user_id_161158_idx')],
                'constraints': [models.UniqueConstraint(fields=('budget', 'user'), name='unique_budget_member')],
            },
        ),
        migrations.RunPython(backfill_owner_memberships, migrations.RunPython.noop),
    ]
